---
swagger: "2.0"
info:
  description: "OpenAPI for RTX"
  version: "1.2.0"
  title: "RTX"
  contact:
    email: "edeutsch@systemsbiology.org"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "rtx.ncats.io"
basePath: "/devED/api/rtx/v1"
tags:
- name: "translate"
  description: "Translate natural language question into a standardized query"
  externalDocs:
    description: "Documentation for the RTX translate function"
    url: "http://rtx.ncats.io/devED/overview.html#translate"
- name: "query"
  description: "Query RTX using a predefined question type"
  externalDocs:
    description: "Documentation for the RTX query function"
    url: "http://rtx.ncats.io/devED/overview.html#query"
- name: "getPubmedMeshNgd"
  description: "Query to get the Normalized Google Distance between two MeSH terms\
    \ based on co-occurance in all PubMed article annotations"
  externalDocs:
    description: "Documentation for the RTX query function"
    url: "http://rtx.ncats.io/devED/overview.html#getPubmedMeshNgd"
- name: "response"
  description: "Request stored responses and results from RTX"
  externalDocs:
    description: "Documentation for the RTX response function"
    url: "http://rtx.ncats.io/devED/overview.html#response"
- name: "exampleQuestions"
  description: "Request a list of example questions that can be answered by the system"
  externalDocs:
    description: "Documentation for the RTX exampleQuestions function"
    url: "http://rtx.ncats.io/devED/overview.html#exampleQuestions"
schemes:
- "http"
paths:
  /translate:
    post:
      tags:
      - "translate"
      summary: "Translate natural language question into a standardized query"
      description: ""
      operationId: "translate"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Question object that needs to be translated"
        required: true
        schema:
          $ref: "#/definitions/Question"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Query"
        400:
          description: "Invalid status value"
      x-swagger-router-controller: "swagger_server.controllers.translate_controller"
  /query:
    post:
      tags:
      - "query"
      summary: "Query RTX using a predefined question type"
      description: ""
      operationId: "query"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Query information to be submitted"
        required: true
        schema:
          $ref: "#/definitions/Query"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Response"
        400:
          description: "Invalid status value"
      x-swagger-router-controller: "swagger_server.controllers.query_controller"
  /getPubmedMeshNgd/{term1}/{term2}:
    get:
      tags:
      - "getPubmedMeshNgd"
      summary: "Query to get the Normalized Google Distance between two MeSH terms\
        \ based on co-occurance in all PubMed article annotations"
      description: ""
      operationId: "get_pubmed_mesh_ngd"
      produces:
      - "application/json"
      parameters:
      - name: "term1"
        in: "path"
        description: "First of two terms. Order not important."
        required: true
        type: "string"
      - name: "term2"
        in: "path"
        description: "Second of two terms. Order not important."
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/MeshNgdResponse"
        400:
          description: "Invalid terms"
      x-swagger-router-controller: "swagger_server.controllers.get_pubmed_mesh_ngd_controller"
  /exampleQuestions:
    get:
      tags:
      - "exampleQuestions"
      summary: "Request a list of example questions that RTX can answer"
      description: ""
      operationId: "example_questions"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
      x-swagger-router-controller: "swagger_server.controllers.example_questions_controller"
  /response/{response_id}:
    get:
      tags:
      - "response"
      summary: "Request stored responses and results from RTX"
      description: ""
      operationId: "get_response"
      produces:
      - "application/json"
      parameters:
      - name: "response_id"
        in: "path"
        description: "Integer identifier of the response to return"
        required: true
        type: "integer"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Response"
        404:
          description: "Response_id not found"
      x-swagger-router-controller: "swagger_server.controllers.response_controller"
  /response/{response_id}/result/{result_id}:
    get:
      tags:
      - "response"
      summary: "Request stored responses and results from RTX"
      description: ""
      operationId: "get_result"
      produces:
      - "application/json"
      parameters:
      - name: "response_id"
        in: "path"
        description: "Integer identifier of the response to return"
        required: true
        type: "integer"
      - name: "result_id"
        in: "path"
        description: "Integer identifier of the result to return"
        required: true
        type: "integer"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Result"
        404:
          description: "result_id not found"
      x-swagger-router-controller: "swagger_server.controllers.response_controller"
  /response/{response_id}/feedback:
    get:
      tags:
      - "response"
      summary: "Request stored feedback for this response from RTX"
      description: ""
      operationId: "get_response_feedback"
      produces:
      - "application/json"
      parameters:
      - name: "response_id"
        in: "path"
        description: "Integer identifier of the response to return"
        required: true
        type: "integer"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ResponseFeedback"
        404:
          description: "Response_id not found"
      x-swagger-router-controller: "swagger_server.controllers.response_controller"
  /response/{response_id}/result/{result_id}/feedback:
    get:
      tags:
      - "response"
      summary: "Request stored feedback for this result from RTX"
      description: ""
      operationId: "get_result_feedback"
      produces:
      - "application/json"
      parameters:
      - name: "response_id"
        in: "path"
        description: "Integer identifier of the response to return"
        required: true
        type: "integer"
      - name: "result_id"
        in: "path"
        description: "Integer identifier of the result to return"
        required: true
        type: "integer"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ResultFeedback"
        404:
          description: "result_id not found"
      x-swagger-router-controller: "swagger_server.controllers.response_controller"
    post:
      tags:
      - "response"
      summary: "Store feedback for a particular result"
      description: ""
      operationId: "post_result_feedback"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "response_id"
        in: "path"
        description: "Integer identifier of the response to return"
        required: true
        type: "integer"
      - name: "result_id"
        in: "path"
        description: "Integer identifier of the result to return"
        required: true
        type: "integer"
      - in: "body"
        name: "body"
        description: "Feedback information to be submitted"
        required: true
        schema:
          $ref: "#/definitions/Query"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Response"
        400:
          description: "Invalid status value"
      x-swagger-router-controller: "swagger_server.controllers.response_controller"
definitions:
  Question:
    type: "object"
    properties:
      text:
        type: "string"
        example: "what genetic conditions offer protection against malaria"
        description: "Free text question"
      language:
        type: "string"
        example: "English"
        description: "Human language in which the question is posed"
        enum:
        - "English"
    example:
      language: "English"
      text: "what genetic conditions offer protection against malaria"
  Query:
    type: "object"
    properties:
      original_question:
        type: "string"
        example: "what genetic conditions offer protection against malaria"
        description: "Original question as it was typed in by the user"
      restated_question:
        type: "string"
        example: "Which genetic conditions may offer protection against malaria?"
        description: "Restatement of the question as understood by the translator"
      message:
        type: "string"
        example: "Your question was understood."
        description: "Response from the translation engine to the user"
      known_query_type_id:
        type: "string"
        example: "Q1"
        description: "RTX identifier for the specific query type"
      bypass_cache:
        type: "string"
        example: "true"
        description: "Set to true in order to bypass any possible cached response\
          \ and try to answer the query over again"
      terms:
        $ref: "#/definitions/Query_terms"
    example:
      original_question: "what genetic conditions offer protection against malaria"
      bypass_cache: "true"
      terms:
        disease: "malaria"
      restated_question: "Which genetic conditions may offer protection against malaria?"
      known_query_type_id: "Q1"
      message: "Your question was understood."
  Response:
    type: "object"
    properties:
      context:
        type: "string"
        example: "http://translator.ncats.io"
        description: "JSON-LD context URI"
      type:
        type: "string"
        example: "medical_translator_query_result"
        description: "Entity type of this response"
      id:
        type: "string"
        example: "http://rtx.ncats.io/devED/api/v1/response/1234"
        description: "URI for this response"
      tool_version:
        type: "string"
        example: "RTX 0.4.0"
        description: "Version label of the tool that generated this response"
      schema_version:
        type: "string"
        example: "0.5"
        description: "Version label of this JSON-LD schema"
      datetime:
        type: "string"
        example: "2018-01-09 12:34:45"
        description: "ISO standard datetime string for the time that this response\
          \ was generated"
      original_question_text:
        type: "string"
        example: "what proteins are affected by sickle cell anemia"
        description: "The original question text typed in by the user"
      restated_question_text:
        type: "string"
        example: "Which proteins are affected by sickle cell anemia?"
        description: "A precise restatement of the question, as understood by the\
          \ Translator, for which the answer applies. The user should verify that\
          \ the restated question matches the intent of their original question (it\
          \ might not)."
      known_query_type_id:
        type: "string"
        example: "Q2"
        description: "The query type id if one is known for the query/response (as\
          \ defined in https://docs.google.com/spreadsheets/d/18zW81wteUfOn3rFRVG0z8mW-ecNhdsfD_6s73ETJnUw/edit#gid=1742835901\
          \ )"
      terms:
        type: "object"
        example: "{ 'disease': 'malaria' }"
        description: "The is string of the query type id if one is known for the query/response"
        properties: {}
      result_code:
        type: "string"
        example: "OK"
        description: "Set to OK for success, or some other short string to indicate\
          \ and error (e.g., KGUnavailable, TermNotFound, etc.)"
      message:
        type: "string"
        example: "1 answer found"
        description: "Extended message denoting the success or mode of failure for\
          \ the response"
      result_list:
        type: "array"
        items:
          $ref: "#/definitions/Result"
    example:
      type: "medical_translator_query_result"
      original_question_text: "what proteins are affected by sickle cell anemia"
      message: "1 answer found"
      schema_version: "0.5"
      datetime: "2018-01-09 12:34:45"
      tool_version: "RTX 0.4.0"
      terms: "{ 'disease': 'malaria' }"
      context: "http://translator.ncats.io"
      known_query_type_id: "Q2"
      result_list:
      - result_type: "answer"
        result_graph:
          node_list:
          - symbol: "HP"
            node_attributes:
            - name: "Wikipedia article"
              type: "article"
              value: "7.23e-12"
              url: "https://en.wikipedia.org/wiki/Malaria"
            - name: "Wikipedia article"
              type: "article"
              value: "7.23e-12"
              url: "https://en.wikipedia.org/wiki/Malaria"
            name: "Haptoglobin"
            description: "Haptoglobin captures, and combines with free plasma hemoglobin..."
            id: "https://www.uniprot.org/uniprot/P00738"
            accession: "OMIM:603903"
            type: "protein"
          - symbol: "HP"
            node_attributes:
            - name: "Wikipedia article"
              type: "article"
              value: "7.23e-12"
              url: "https://en.wikipedia.org/wiki/Malaria"
            - name: "Wikipedia article"
              type: "article"
              value: "7.23e-12"
              url: "https://en.wikipedia.org/wiki/Malaria"
            name: "Haptoglobin"
            description: "Haptoglobin captures, and combines with free plasma hemoglobin..."
            id: "https://www.uniprot.org/uniprot/P00738"
            accession: "OMIM:603903"
            type: "protein"
          edge_list:
          - confidence: 0.99
            target_id: "https://www.uniprot.org/uniprot/P00738"
            source_id: "http://omim.org/entry/603903"
            type: "affects"
            origin_list:
            - attribute_list:
              - name: "Orthopaedic Manifestations of Sickle Cell Disease"
                type: "PubMed_article"
                value: "0.5"
                url: "https://www.ncbi.nlm.nih.gov/pubmed/29309293"
              - name: "Orthopaedic Manifestations of Sickle Cell Disease"
                type: "PubMed_article"
                value: "0.5"
                url: "https://www.ncbi.nlm.nih.gov/pubmed/29309293"
              name: "Wikipedia article"
              id: "https://api.monarchinitiative.org/api/bioentity/disease/OMIM:603903/genes/"
              type: "Monarch_BioLink_API_Relationship"
            - attribute_list:
              - name: "Orthopaedic Manifestations of Sickle Cell Disease"
                type: "PubMed_article"
                value: "0.5"
                url: "https://www.ncbi.nlm.nih.gov/pubmed/29309293"
              - name: "Orthopaedic Manifestations of Sickle Cell Disease"
                type: "PubMed_article"
                value: "0.5"
                url: "https://www.ncbi.nlm.nih.gov/pubmed/29309293"
              name: "Wikipedia article"
              id: "https://api.monarchinitiative.org/api/bioentity/disease/OMIM:603903/genes/"
              type: "Monarch_BioLink_API_Relationship"
          - confidence: 0.99
            target_id: "https://www.uniprot.org/uniprot/P00738"
            source_id: "http://omim.org/entry/603903"
            type: "affects"
            origin_list:
            - attribute_list:
              - name: "Orthopaedic Manifestations of Sickle Cell Disease"
                type: "PubMed_article"
                value: "0.5"
                url: "https://www.ncbi.nlm.nih.gov/pubmed/29309293"
              - name: "Orthopaedic Manifestations of Sickle Cell Disease"
                type: "PubMed_article"
                value: "0.5"
                url: "https://www.ncbi.nlm.nih.gov/pubmed/29309293"
              name: "Wikipedia article"
              id: "https://api.monarchinitiative.org/api/bioentity/disease/OMIM:603903/genes/"
              type: "Monarch_BioLink_API_Relationship"
            - attribute_list:
              - name: "Orthopaedic Manifestations of Sickle Cell Disease"
                type: "PubMed_article"
                value: "0.5"
                url: "https://www.ncbi.nlm.nih.gov/pubmed/29309293"
              - name: "Orthopaedic Manifestations of Sickle Cell Disease"
                type: "PubMed_article"
                value: "0.5"
                url: "https://www.ncbi.nlm.nih.gov/pubmed/29309293"
              name: "Wikipedia article"
              id: "https://api.monarchinitiative.org/api/bioentity/disease/OMIM:603903/genes/"
              type: "Monarch_BioLink_API_Relationship"
        confidence: 0.9234
        id: "http://rtx.ncats.io/devED/api/v1/response/1234/result/2345"
        text: "The genetic condition sickle cell anemia may provide protection from\
          \ cerebral malaria via genetic alterations of proteins HBB (P68871) and\
          \ HMOX1 (P09601)."
      - result_type: "answer"
        result_graph:
          node_list:
          - symbol: "HP"
            node_attributes:
            - name: "Wikipedia article"
              type: "article"
              value: "7.23e-12"
              url: "https://en.wikipedia.org/wiki/Malaria"
            - name: "Wikipedia article"
              type: "article"
              value: "7.23e-12"
              url: "https://en.wikipedia.org/wiki/Malaria"
            name: "Haptoglobin"
            description: "Haptoglobin captures, and combines with free plasma hemoglobin..."
            id: "https://www.uniprot.org/uniprot/P00738"
            accession: "OMIM:603903"
            type: "protein"
          - symbol: "HP"
            node_attributes:
            - name: "Wikipedia article"
              type: "article"
              value: "7.23e-12"
              url: "https://en.wikipedia.org/wiki/Malaria"
            - name: "Wikipedia article"
              type: "article"
              value: "7.23e-12"
              url: "https://en.wikipedia.org/wiki/Malaria"
            name: "Haptoglobin"
            description: "Haptoglobin captures, and combines with free plasma hemoglobin..."
            id: "https://www.uniprot.org/uniprot/P00738"
            accession: "OMIM:603903"
            type: "protein"
          edge_list:
          - confidence: 0.99
            target_id: "https://www.uniprot.org/uniprot/P00738"
            source_id: "http://omim.org/entry/603903"
            type: "affects"
            origin_list:
            - attribute_list:
              - name: "Orthopaedic Manifestations of Sickle Cell Disease"
                type: "PubMed_article"
                value: "0.5"
                url: "https://www.ncbi.nlm.nih.gov/pubmed/29309293"
              - name: "Orthopaedic Manifestations of Sickle Cell Disease"
                type: "PubMed_article"
                value: "0.5"
                url: "https://www.ncbi.nlm.nih.gov/pubmed/29309293"
              name: "Wikipedia article"
              id: "https://api.monarchinitiative.org/api/bioentity/disease/OMIM:603903/genes/"
              type: "Monarch_BioLink_API_Relationship"
            - attribute_list:
              - name: "Orthopaedic Manifestations of Sickle Cell Disease"
                type: "PubMed_article"
                value: "0.5"
                url: "https://www.ncbi.nlm.nih.gov/pubmed/29309293"
              - name: "Orthopaedic Manifestations of Sickle Cell Disease"
                type: "PubMed_article"
                value: "0.5"
                url: "https://www.ncbi.nlm.nih.gov/pubmed/29309293"
              name: "Wikipedia article"
              id: "https://api.monarchinitiative.org/api/bioentity/disease/OMIM:603903/genes/"
              type: "Monarch_BioLink_API_Relationship"
          - confidence: 0.99
            target_id: "https://www.uniprot.org/uniprot/P00738"
            source_id: "http://omim.org/entry/603903"
            type: "affects"
            origin_list:
            - attribute_list:
              - name: "Orthopaedic Manifestations of Sickle Cell Disease"
                type: "PubMed_article"
                value: "0.5"
                url: "https://www.ncbi.nlm.nih.gov/pubmed/29309293"
              - name: "Orthopaedic Manifestations of Sickle Cell Disease"
                type: "PubMed_article"
                value: "0.5"
                url: "https://www.ncbi.nlm.nih.gov/pubmed/29309293"
              name: "Wikipedia article"
              id: "https://api.monarchinitiative.org/api/bioentity/disease/OMIM:603903/genes/"
              type: "Monarch_BioLink_API_Relationship"
            - attribute_list:
              - name: "Orthopaedic Manifestations of Sickle Cell Disease"
                type: "PubMed_article"
                value: "0.5"
                url: "https://www.ncbi.nlm.nih.gov/pubmed/29309293"
              - name: "Orthopaedic Manifestations of Sickle Cell Disease"
                type: "PubMed_article"
                value: "0.5"
                url: "https://www.ncbi.nlm.nih.gov/pubmed/29309293"
              name: "Wikipedia article"
              id: "https://api.monarchinitiative.org/api/bioentity/disease/OMIM:603903/genes/"
              type: "Monarch_BioLink_API_Relationship"
        confidence: 0.9234
        id: "http://rtx.ncats.io/devED/api/v1/response/1234/result/2345"
        text: "The genetic condition sickle cell anemia may provide protection from\
          \ cerebral malaria via genetic alterations of proteins HBB (P68871) and\
          \ HMOX1 (P09601)."
      result_code: "OK"
      id: "http://rtx.ncats.io/devED/api/v1/response/1234"
      restated_question_text: "Which proteins are affected by sickle cell anemia?"
  Result:
    type: "object"
    properties:
      id:
        type: "string"
        example: "http://rtx.ncats.io/devED/api/v1/response/1234/result/2345"
        description: "URI for this response"
      text:
        type: "string"
        example: "The genetic condition sickle cell anemia may provide protection\
          \ from cerebral malaria via genetic alterations of proteins HBB (P68871)\
          \ and HMOX1 (P09601)."
        description: "A free text description or comment from the reasoner about this\
          \ answer"
      confidence:
        type: "number"
        format: "float"
        example: 0.9234
        description: "Confidence metric for this result, a value 0.0 (no confidence)\
          \ and 1.0 (highest confidence)"
      result_type:
        type: "string"
        example: "answer"
        description: "One of several possible result types: 'individual query answer',\
          \ 'neighborhood graph', 'type summary graph'"
      result_graph:
        $ref: "#/definitions/Result_graph"
    description: "One of potentially several results or answers for a query"
    example:
      result_type: "answer"
      result_graph:
        node_list:
        - symbol: "HP"
          node_attributes:
          - name: "Wikipedia article"
            type: "article"
            value: "7.23e-12"
            url: "https://en.wikipedia.org/wiki/Malaria"
          - name: "Wikipedia article"
            type: "article"
            value: "7.23e-12"
            url: "https://en.wikipedia.org/wiki/Malaria"
          name: "Haptoglobin"
          description: "Haptoglobin captures, and combines with free plasma hemoglobin..."
          id: "https://www.uniprot.org/uniprot/P00738"
          accession: "OMIM:603903"
          type: "protein"
        - symbol: "HP"
          node_attributes:
          - name: "Wikipedia article"
            type: "article"
            value: "7.23e-12"
            url: "https://en.wikipedia.org/wiki/Malaria"
          - name: "Wikipedia article"
            type: "article"
            value: "7.23e-12"
            url: "https://en.wikipedia.org/wiki/Malaria"
          name: "Haptoglobin"
          description: "Haptoglobin captures, and combines with free plasma hemoglobin..."
          id: "https://www.uniprot.org/uniprot/P00738"
          accession: "OMIM:603903"
          type: "protein"
        edge_list:
        - confidence: 0.99
          target_id: "https://www.uniprot.org/uniprot/P00738"
          source_id: "http://omim.org/entry/603903"
          type: "affects"
          origin_list:
          - attribute_list:
            - name: "Orthopaedic Manifestations of Sickle Cell Disease"
              type: "PubMed_article"
              value: "0.5"
              url: "https://www.ncbi.nlm.nih.gov/pubmed/29309293"
            - name: "Orthopaedic Manifestations of Sickle Cell Disease"
              type: "PubMed_article"
              value: "0.5"
              url: "https://www.ncbi.nlm.nih.gov/pubmed/29309293"
            name: "Wikipedia article"
            id: "https://api.monarchinitiative.org/api/bioentity/disease/OMIM:603903/genes/"
            type: "Monarch_BioLink_API_Relationship"
          - attribute_list:
            - name: "Orthopaedic Manifestations of Sickle Cell Disease"
              type: "PubMed_article"
              value: "0.5"
              url: "https://www.ncbi.nlm.nih.gov/pubmed/29309293"
            - name: "Orthopaedic Manifestations of Sickle Cell Disease"
              type: "PubMed_article"
              value: "0.5"
              url: "https://www.ncbi.nlm.nih.gov/pubmed/29309293"
            name: "Wikipedia article"
            id: "https://api.monarchinitiative.org/api/bioentity/disease/OMIM:603903/genes/"
            type: "Monarch_BioLink_API_Relationship"
        - confidence: 0.99
          target_id: "https://www.uniprot.org/uniprot/P00738"
          source_id: "http://omim.org/entry/603903"
          type: "affects"
          origin_list:
          - attribute_list:
            - name: "Orthopaedic Manifestations of Sickle Cell Disease"
              type: "PubMed_article"
              value: "0.5"
              url: "https://www.ncbi.nlm.nih.gov/pubmed/29309293"
            - name: "Orthopaedic Manifestations of Sickle Cell Disease"
              type: "PubMed_article"
              value: "0.5"
              url: "https://www.ncbi.nlm.nih.gov/pubmed/29309293"
            name: "Wikipedia article"
            id: "https://api.monarchinitiative.org/api/bioentity/disease/OMIM:603903/genes/"
            type: "Monarch_BioLink_API_Relationship"
          - attribute_list:
            - name: "Orthopaedic Manifestations of Sickle Cell Disease"
              type: "PubMed_article"
              value: "0.5"
              url: "https://www.ncbi.nlm.nih.gov/pubmed/29309293"
            - name: "Orthopaedic Manifestations of Sickle Cell Disease"
              type: "PubMed_article"
              value: "0.5"
              url: "https://www.ncbi.nlm.nih.gov/pubmed/29309293"
            name: "Wikipedia article"
            id: "https://api.monarchinitiative.org/api/bioentity/disease/OMIM:603903/genes/"
            type: "Monarch_BioLink_API_Relationship"
      confidence: 0.9234
      id: "http://rtx.ncats.io/devED/api/v1/response/1234/result/2345"
      text: "The genetic condition sickle cell anemia may provide protection from\
        \ cerebral malaria via genetic alterations of proteins HBB (P68871) and HMOX1\
        \ (P09601)."
  Result_graph:
    type: "object"
    properties:
      node_list:
        type: "array"
        items:
          $ref: "#/definitions/Node"
      edge_list:
        type: "array"
        items:
          $ref: "#/definitions/Edge"
    description: "A thought graph associated with this result. This will commonly\
      \ be a linear path subgraph from one concept to another, but related items aside\
      \ of the path may be included."
    example:
      node_list:
      - symbol: "HP"
        node_attributes:
        - name: "Wikipedia article"
          type: "article"
          value: "7.23e-12"
          url: "https://en.wikipedia.org/wiki/Malaria"
        - name: "Wikipedia article"
          type: "article"
          value: "7.23e-12"
          url: "https://en.wikipedia.org/wiki/Malaria"
        name: "Haptoglobin"
        description: "Haptoglobin captures, and combines with free plasma hemoglobin..."
        id: "https://www.uniprot.org/uniprot/P00738"
        accession: "OMIM:603903"
        type: "protein"
      - symbol: "HP"
        node_attributes:
        - name: "Wikipedia article"
          type: "article"
          value: "7.23e-12"
          url: "https://en.wikipedia.org/wiki/Malaria"
        - name: "Wikipedia article"
          type: "article"
          value: "7.23e-12"
          url: "https://en.wikipedia.org/wiki/Malaria"
        name: "Haptoglobin"
        description: "Haptoglobin captures, and combines with free plasma hemoglobin..."
        id: "https://www.uniprot.org/uniprot/P00738"
        accession: "OMIM:603903"
        type: "protein"
      edge_list:
      - confidence: 0.99
        target_id: "https://www.uniprot.org/uniprot/P00738"
        source_id: "http://omim.org/entry/603903"
        type: "affects"
        origin_list:
        - attribute_list:
          - name: "Orthopaedic Manifestations of Sickle Cell Disease"
            type: "PubMed_article"
            value: "0.5"
            url: "https://www.ncbi.nlm.nih.gov/pubmed/29309293"
          - name: "Orthopaedic Manifestations of Sickle Cell Disease"
            type: "PubMed_article"
            value: "0.5"
            url: "https://www.ncbi.nlm.nih.gov/pubmed/29309293"
          name: "Wikipedia article"
          id: "https://api.monarchinitiative.org/api/bioentity/disease/OMIM:603903/genes/"
          type: "Monarch_BioLink_API_Relationship"
        - attribute_list:
          - name: "Orthopaedic Manifestations of Sickle Cell Disease"
            type: "PubMed_article"
            value: "0.5"
            url: "https://www.ncbi.nlm.nih.gov/pubmed/29309293"
          - name: "Orthopaedic Manifestations of Sickle Cell Disease"
            type: "PubMed_article"
            value: "0.5"
            url: "https://www.ncbi.nlm.nih.gov/pubmed/29309293"
          name: "Wikipedia article"
          id: "https://api.monarchinitiative.org/api/bioentity/disease/OMIM:603903/genes/"
          type: "Monarch_BioLink_API_Relationship"
      - confidence: 0.99
        target_id: "https://www.uniprot.org/uniprot/P00738"
        source_id: "http://omim.org/entry/603903"
        type: "affects"
        origin_list:
        - attribute_list:
          - name: "Orthopaedic Manifestations of Sickle Cell Disease"
            type: "PubMed_article"
            value: "0.5"
            url: "https://www.ncbi.nlm.nih.gov/pubmed/29309293"
          - name: "Orthopaedic Manifestations of Sickle Cell Disease"
            type: "PubMed_article"
            value: "0.5"
            url: "https://www.ncbi.nlm.nih.gov/pubmed/29309293"
          name: "Wikipedia article"
          id: "https://api.monarchinitiative.org/api/bioentity/disease/OMIM:603903/genes/"
          type: "Monarch_BioLink_API_Relationship"
        - attribute_list:
          - name: "Orthopaedic Manifestations of Sickle Cell Disease"
            type: "PubMed_article"
            value: "0.5"
            url: "https://www.ncbi.nlm.nih.gov/pubmed/29309293"
          - name: "Orthopaedic Manifestations of Sickle Cell Disease"
            type: "PubMed_article"
            value: "0.5"
            url: "https://www.ncbi.nlm.nih.gov/pubmed/29309293"
          name: "Wikipedia article"
          id: "https://api.monarchinitiative.org/api/bioentity/disease/OMIM:603903/genes/"
          type: "Monarch_BioLink_API_Relationship"
  Node:
    type: "object"
    properties:
      type:
        type: "string"
        example: "protein"
        description: "Entity type of this node (e.g., protein, disease, etc.)"
      id:
        type: "string"
        example: "https://www.uniprot.org/uniprot/P00738"
        description: "URI identifier for this response"
      symbol:
        type: "string"
        example: "HP"
        description: "Short abbreviation or symbol for this entity"
      name:
        type: "string"
        example: "Haptoglobin"
        description: "Formal name of the entity"
      accession:
        type: "string"
        example: "OMIM:603903"
        description: "Accession number in an external resource for this entity"
      description:
        type: "string"
        example: "Haptoglobin captures, and combines with free plasma hemoglobin..."
        description: "One to three sentences of description/definition of this entity"
      node_attributes:
        type: "array"
        description: "A list of arbitrary attributes for the node"
        items:
          $ref: "#/definitions/Node_attribute"
    description: "A node in the thought subgraph"
    example:
      symbol: "HP"
      node_attributes:
      - name: "Wikipedia article"
        type: "article"
        value: "7.23e-12"
        url: "https://en.wikipedia.org/wiki/Malaria"
      - name: "Wikipedia article"
        type: "article"
        value: "7.23e-12"
        url: "https://en.wikipedia.org/wiki/Malaria"
      name: "Haptoglobin"
      description: "Haptoglobin captures, and combines with free plasma hemoglobin..."
      id: "https://www.uniprot.org/uniprot/P00738"
      accession: "OMIM:603903"
      type: "protein"
  Node_attribute:
    type: "object"
    properties:
      type:
        type: "string"
        example: "article"
        description: "Entity type of this attribute"
      name:
        type: "string"
        example: "Wikipedia article"
        description: "Formal name of the attribute"
      value:
        type: "string"
        example: "7.23e-12"
        description: "Value of the attribute"
      url:
        type: "string"
        example: "https://en.wikipedia.org/wiki/Malaria"
        description: "A URL corresponding to this attribute"
    description: "A generic attribute for a node"
    example:
      name: "Wikipedia article"
      type: "article"
      value: "7.23e-12"
      url: "https://en.wikipedia.org/wiki/Malaria"
  Edge:
    type: "object"
    properties:
      type:
        type: "string"
        example: "affects"
        description: "Entity type of this response"
      source_id:
        type: "string"
        example: "http://omim.org/entry/603903"
        description: "Corresponds to the @id of source node of this edge"
      target_id:
        type: "string"
        example: "https://www.uniprot.org/uniprot/P00738"
        description: "Corresponds to the @id of target node of this edge"
      confidence:
        type: "number"
        format: "float"
        example: 0.99
        description: "Confidence metric for this edge, a value 0.0 (no confidence)\
          \ and 1.0 (highest confidence)"
      origin_list:
        type: "array"
        description: "A list of origins (sources) for this edge and attributes from\
          \ those origins"
        items:
          $ref: "#/definitions/Origin"
    description: "An edge in the thought subgraph linking two nodes"
    example:
      confidence: 0.99
      target_id: "https://www.uniprot.org/uniprot/P00738"
      source_id: "http://omim.org/entry/603903"
      type: "affects"
      origin_list:
      - attribute_list:
        - name: "Orthopaedic Manifestations of Sickle Cell Disease"
          type: "PubMed_article"
          value: "0.5"
          url: "https://www.ncbi.nlm.nih.gov/pubmed/29309293"
        - name: "Orthopaedic Manifestations of Sickle Cell Disease"
          type: "PubMed_article"
          value: "0.5"
          url: "https://www.ncbi.nlm.nih.gov/pubmed/29309293"
        name: "Wikipedia article"
        id: "https://api.monarchinitiative.org/api/bioentity/disease/OMIM:603903/genes/"
        type: "Monarch_BioLink_API_Relationship"
      - attribute_list:
        - name: "Orthopaedic Manifestations of Sickle Cell Disease"
          type: "PubMed_article"
          value: "0.5"
          url: "https://www.ncbi.nlm.nih.gov/pubmed/29309293"
        - name: "Orthopaedic Manifestations of Sickle Cell Disease"
          type: "PubMed_article"
          value: "0.5"
          url: "https://www.ncbi.nlm.nih.gov/pubmed/29309293"
        name: "Wikipedia article"
        id: "https://api.monarchinitiative.org/api/bioentity/disease/OMIM:603903/genes/"
        type: "Monarch_BioLink_API_Relationship"
  Origin:
    type: "object"
    properties:
      id:
        type: "string"
        example: "https://api.monarchinitiative.org/api/bioentity/disease/OMIM:603903/genes/"
        description: "URI for the origin of the edge"
      type:
        type: "string"
        example: "Monarch_BioLink_API_Relationship"
        description: "Entity type of the origin"
      name:
        type: "string"
        example: "Wikipedia article"
        description: "Formal name of the piece evidence that yielded the edge"
      attribute_list:
        type: "array"
        description: "A list of attributes for this edge from this origin (source)"
        items:
          $ref: "#/definitions/Edge_attribute"
    description: "An origin (source) for this edge"
    example:
      attribute_list:
      - name: "Orthopaedic Manifestations of Sickle Cell Disease"
        type: "PubMed_article"
        value: "0.5"
        url: "https://www.ncbi.nlm.nih.gov/pubmed/29309293"
      - name: "Orthopaedic Manifestations of Sickle Cell Disease"
        type: "PubMed_article"
        value: "0.5"
        url: "https://www.ncbi.nlm.nih.gov/pubmed/29309293"
      name: "Wikipedia article"
      id: "https://api.monarchinitiative.org/api/bioentity/disease/OMIM:603903/genes/"
      type: "Monarch_BioLink_API_Relationship"
  Edge_attribute:
    type: "object"
    properties:
      type:
        type: "string"
        example: "PubMed_article"
        description: "Entity type of this attribute"
      name:
        type: "string"
        example: "Orthopaedic Manifestations of Sickle Cell Disease"
        description: "Formal name of the attribute"
      value:
        type: "string"
        example: "0.5"
        description: "Value of the attribute. While all attributes should have a name,\
          \ many will not have a value"
      url:
        type: "string"
        example: "https://www.ncbi.nlm.nih.gov/pubmed/29309293"
        description: "A URL corresponding to this attribute"
    description: "A generic attribute for an edge"
    example:
      name: "Orthopaedic Manifestations of Sickle Cell Disease"
      type: "PubMed_article"
      value: "0.5"
      url: "https://www.ncbi.nlm.nih.gov/pubmed/29309293"
  MeshNgdResponse:
    type: "object"
    properties:
      result_code:
        type: "string"
        example: "TermNotFound"
        description: "Set to OK for success, or some other short string to indicate\
          \ and error (e.g., TermNotFound, etc.)"
      message:
        type: "string"
        example: "Term 1 'malria' not found in MeSH"
        description: "Extended message denoting the success or mode of failure for\
          \ request"
      value:
        type: "number"
        format: "float"
        example: 0.714
        description: "Calculated Normalized Google Distance for the two supplied terms"
    example:
      result_code: "TermNotFound"
      message: "Term 1 'malria' not found in MeSH"
      value: 0.714
  ResultFeedback:
    type: "object"
    properties:
      id:
        type: "string"
        example: "http://rtx.ncats.io/devED/api/v1/response/1234/result/2345/feedback/4567"
        description: "URI for this feedback item"
      result_id:
        type: "string"
        example: "http://rtx.ncats.io/devED/api/v1/response/1234/result/2345"
        description: "URI for the result that this feedback corresponds to"
      expertise_level_id:
        type: "integer"
        example: 1
        description: "Identifier of the claimed expertise level"
      rating_id:
        type: "integer"
        example: 1
        description: "Identifier of the applied rating"
      comment:
        type: "string"
        example: "This is a great result because..."
        description: "A free text comment about this result"
    description: "Feedback for one result"
    example:
      rating_id: 1
      result_id: "http://rtx.ncats.io/devED/api/v1/response/1234/result/2345"
      expertise_level_id: 1
      comment: "This is a great result because..."
      id: "http://rtx.ncats.io/devED/api/v1/response/1234/result/2345/feedback/4567"
  ResponseFeedback:
    type: "object"
    properties:
      result_feedback_list:
        type: "array"
        items:
          $ref: "#/definitions/ResultFeedback"
    description: "Feedback for all the results corresponding to this result"
    example:
      result_feedback_list:
      - rating_id: 1
        result_id: "http://rtx.ncats.io/devED/api/v1/response/1234/result/2345"
        expertise_level_id: 1
        comment: "This is a great result because..."
        id: "http://rtx.ncats.io/devED/api/v1/response/1234/result/2345/feedback/4567"
      - rating_id: 1
        result_id: "http://rtx.ncats.io/devED/api/v1/response/1234/result/2345"
        expertise_level_id: 1
        comment: "This is a great result because..."
        id: "http://rtx.ncats.io/devED/api/v1/response/1234/result/2345/feedback/4567"
  Query_terms:
    properties:
      disease:
        type: "string"
        example: "malaria"
    description: "Dict of terms needed by the specific query type"
    example:
      disease: "malaria"
externalDocs:
  description: "Documentation for the RTX web service"
  url: "http://rtx.ncats.io/devED/overview.html"
